# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SwiftLint' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for SwiftLint

end
